=== nemi-dev/dfm-view/schema/base_attrs.json
{
  "$schema": "http://json-schema.org/schema",
  "type":"object",
  "properties": {
    "name" :  { "type" : "string", "description": "아이템/세트/스킬/버프 이름" },
    "image" : { "type": "string", "description": "아이템 아이콘 이름" },
    "overlay" : { "type": "string", "description": "아이템 오버레이 아이콘 이름 (환영극단 2막 등)"},
    "level" : { "type" : "number", "description": "아이템 레벨" },
    "itype" : { 
      "$ref": "./itype.json"
    },
    "rarity":   { "type": "string", "description": "레어도",
    "enum": ["Common", "Uncommon", "Rare", "Unique", "Epic"] },
    "material": { "type": "string", "description": "(방어구일 때만) 재질", "enum": ["천", "가죽", "경갑", "중갑", "판금"]},
    "setOf":    {
      "description": "이 아이템으로 활성화시킬 수 있는 세트 [ex) 에픽 환영극단, 개막/종막] ",
      "oneOf": [
        { "type" : "string" },
        {
          "type" : "array",
          "items": {
            "type": "string"
          }
        }
      ]
    },
    "strn":     { "type" : "number", "description": "힘" },
    "intl":     { "type" : "number", "description": "지능" },
    "str_inc":  { "type" : "number", "description": "힘 증가 (%)" },
    "int_inc":  { "type" : "number", "description": "지능 증가 (%)" },
    "atk_ph":   { "type" : "number", "description": "물리 공격력" },
    "atk_mg":   { "type" : "number", "description": "마법 공격력" },
    "atk_ph_inc":    { "type" : "number", "description": "물리 공격력 증가 (%)" },
    "atk_mg_inc":    { "type" : "number", "description": "마법 공격력 증가 (%)" },
    "crit_ph":  { "type" : "number", "description": "물리 크리티컬" },
    "crit_mg":  { "type" : "number", "description": "마법 크리티컬" },
    "crit_ph_pct":   { "type" : "number", "description": "물리 크리티컬 확률 증가 (%)" },
    "crit_mg_pct":   { "type" : "number", "description": "마법 크리티컬 확률 증가 (%)" },

    "dmg_inc":  { "type" : "number", "description": "데미지 증가 (%)" },
    "cdmg_inc" :   { "type" : "number", "description": "크리티컬 데미지 증가 (%)" },
    "dmg_add":  { "type" : "number", "description": "추가 데미지 (%)" },
    "eltype":   {
      "description": "속성 부여",
      "oneOf": [
        {
          "type": "string",
          "enum": ["화", "수", "명", "암"]
        },
        {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["화", "수", "명", "암"]
          }
        }
      ]
    },
    "el_fire":  { "type" : "number", "description": "화속성 강화" },
    "el_ice":   { "type" : "number", "description": "수속성 강화" },
    "el_lght":  { "type" : "number", "description": "명속성 강화" },
    "el_dark":  { "type" : "number", "description": "암속성 강화" },
    "eldmg_fire": { "type" : "number", "description": "화속성 추가 데미지 (%)" },
    "eldmg_ice":  { "type" : "number", "description": "수속성 추가 데미지 (%)" },
    "eldmg_lght": { "type" : "number", "description": "명속성 추가 데미지 (%)" },
    "eldmg_dark": { "type" : "number", "description": "암속성 추가 데미지 (%)" },
    "sk_inc" :   { "type" : "number", "description": "스킬 공격력 증가 (%)" },
    "sk_inc_sum" :   { "type" : "number", "description": "단리 적용되는 (ex. 패시브 스킬) 스킬 공격력 증가 (%)" },
    "sk_val" :  { "type" : "object", "description": "특정 스킬 공격력 증가", "patternProperties": { ".*" : { "type" : "number" } } },
    "sk_hit" :  { "type" : "object", "description": "스킬 1회 사용 시 타격횟수 증가", "patternProperties": { ".*" : { "type" : "number" } } },
    "sk_lv" :  { "type" : "object", "description": "특정 스킬 레벨 증가", "patternProperties": { ".*" : { "type" : "number" } } },
    "sk_cool" :  { "type" : "object", "description": "특정 스킬 쿨타임 증가/감소 (%)", "patternProperties": { ".*" : { "type" : "number" } }},
    "target_def" : { "type" : "number", "description": "적 방어력 변화 (내가 공격한 적 + 방어 감소 오라 모두 포함)" },
    "target_res" : { "type" : "number", "description": "적 속성저항 변화 (모든속성)" },

    "speed_atk": { "type": "number", "description": "공격 속도 +X%" },
    "speed_cast": { "type": "number", "description": "캐스팅 속도 +X%" },
    "speed_move": { "type": "number", "description": "이동 속도 +X%" },
    "Accu":       { "type" : "number", "description": "적중" },
    "AccuPct":   { "type" : "number", "description": "적중 확률 증가 (%)" },

    "hpmax": { "type": "number", "description": "HP MAX (실적용 제외)" },
    "mpmax": { "type": "number", "description": "MP MAX (실적용 제외)" },
    "vit": { "type": "number", "description": "체력" },
    "psi": { "type": "number", "description": "정신력" },
    "def_ph": { "type": "number", "description": "물리 방어력" },
    "def_mg": { "type": "number", "description": "마법 방어력" },
    "def_ph_pct": { "type": "number", "description": "물리 방어력 (%)" },
    "def_mg_pct": { "type": "number", "description": "마법 방어력 (%)" },
    "res_fire":  { "type" : "number", "description": "화속성 저항" },
    "res_ice":   { "type" : "number", "description": "수속성 저항" },
    "res_lght":  { "type" : "number", "description": "명속성 저항" },
    "res_dark":  { "type" : "number", "description": "암속성 저항" },
    
    "maxRepeat" : { "type" : "number", "description": "최대 중첩 횟수", "default" : 1 },
    "misc" : { "type" : "array", "description": "기타 관심없는 효과", "items": { "type" : "string" }}
  }
}

=== nemi-dev/dfm-view/data/armorbase.json
[
  {
    "name": "<60에픽 천 상의>",
    "level": 60, "rarity": "Epic", "material": "천", "itype": "상의", 
    "def_ph": 2598,
    "strn": 24,
    "intl": 36,
    "psi": 36,
    "speed_atk": 2,
    "speed_cast": 4
  },
  {
    "name": "<60에픽 천 하의>",
    "level": 60, "rarity": "Epic", "material": "천", "itype": "하의", 
    "def_ph": 2165,
    "strn": 24,
    "intl": 36,
    "psi": 36,
    "speed_atk": 2,
    "speed_cast": 4
  },
  {
    "name": "<60에픽 천 머리어깨>",
    "level": 60, "rarity": "Epic", "material": "천", "itype": "머리어깨",
    "def_ph": 1731,
    "strn": 19,
    "intl": 29,
    "psi": 29,
    "speed_atk": 2,
    "speed_cast": 4
  },
  {
    "name": "<60에픽 천 벨트>",
    "level": 60, "rarity": "Epic", "material": "천", "itype": "벨트",
    "def_ph": 866,
    "strn": 14,
    "intl": 22,
    "psi": 22,
    "speed_atk": 2,
    "speed_cast": 4
  },
  {
    "name": "<60에픽 천 신발>",
    "level": 60, "rarity": "Epic", "material": "천", "itype": "신발",
    "def_ph": 1299,
    "strn": 14,
    "intl": 22,
    "psi": 22,
    "speed_move": 4
  },
  {
    "name": "<60에픽 가죽 상의>",
    "level": 60, "rarity": "Epic", "material": "가죽", "itype": "상의", 
    "def_ph": 3117,
    "strn": 30,
    "intl": 30,
    "psi": 33,
    "speed_atk": 3
  },
  {
    "name": "<60에픽 가죽 하의>",
    "level": 60, "rarity": "Epic", "material": "가죽", "itype": "하의", 
    "def_ph": 2598,
    "strn": 30,
    "intl": 30,
    "psi": 33,
    "speed_atk": 3
  },
  {
    "name": "<60에픽 가죽 머리어깨>",
    "level": 60, "rarity": "Epic", "material": "가죽", "itype": "머리어깨",
    "def_ph": 2078,
    "strn": 24,
    "intl": 24,
    "psi": 26,
    "speed_atk": 3
  },
  {
    "name": "<60에픽 가죽 벨트>",
    "level": 60, "rarity": "Epic", "material": "가죽", "itype": "벨트",
    "def_ph": 1038,
    "strn": 18,
    "intl": 18,
    "psi": 19,
    "speed_atk": 3
  },
  {
    "name": "<60에픽 가죽 신발>",
    "level": 60, "rarity": "Epic", "material": "가죽", "itype": "신발",
    "def_ph": 1559,
    "strn": 18,
    "intl": 18,
    "psi": 19,
    "speed_move": 4
  },
  {
    "name": "<60에픽 경갑 상의>",
    "level": 60, "rarity": "Epic", "material": "경갑", "itype": "상의", 
    "def_ph": 4157,
    "strn": 36,
    "intl": 24,
    "speed_atk": 2
  },
  {
    "name": "<60에픽 경갑 하의>",
    "level": 60, "rarity": "Epic", "material": "경갑", "itype": "하의", 
    "def_ph": 3465,
    "strn": 36,
    "intl": 24,
    "speed_atk": 2
  },
  {
    "name": "<60에픽 경갑 머리어깨>",
    "level": 60, "rarity": "Epic", "material": "경갑", "itype": "머리어깨",
    "def_ph": 2771,
    "strn": 29,
    "intl": 19,
    "speed_atk": 2
  },
  {
    "name": "<60에픽 경갑 벨트>",
    "level": 60, "rarity": "Epic", "material": "경갑", "itype": "벨트",
    "def_ph": 1385,
    "strn": 22,
    "intl": 14,
    "speed_atk": 2
  },
  {
    "name": "<60에픽 경갑 신발>",
    "level": 60, "rarity": "Epic", "material": "경갑", "itype": "신발",
    "def_ph": 2078,
    "strn": 22,
    "intl": 14,
    "speed_move": 4
  },
  {
    "name": "<60에픽 중갑 상의>",
    "level": 60, "rarity": "Epic", "material": "중갑", "itype": "상의", 
    "def_ph": 4677,
    "strn": 33,
    "intl": 24,
    "vit": 30,
    "speed_atk": 1
  },
  {
    "name": "<60에픽 중갑 하의>",
    "level": 60, "rarity": "Epic", "material": "중갑", "itype": "하의", 
    "def_ph": 3897,
    "strn": 33,
    "intl": 24,
    "vit": 30,
    "speed_atk": 1
  },
  {
    "name": "<60에픽 중갑 머리어깨>",
    "level": 60, "rarity": "Epic", "material": "중갑", "itype": "머리어깨",
    "def_ph": 3117,
    "strn": 26,
    "intl": 19,
    "vit": 24,
    "speed_atk": 1
  },
  {
    "name": "<60에픽 중갑 벨트>",
    "level": 60, "rarity": "Epic", "material": "중갑", "itype": "벨트",
    "def_ph": 1559,
    "strn": 19,
    "intl": 14,
    "vit": 18,
    "speed_atk": 1
  },
  {
    "name": "<60에픽 중갑 신발>",
    "level": 60, "rarity": "Epic", "material": "중갑", "itype": "신발",
    "def_ph": 2339,
    "strn": 19,
    "intl": 14,
    "vit": 18,
    "speed_move": 4
  },
  {
    "name": "<60에픽 판금 상의>",
    "level": 60, "rarity": "Epic", "material": "판금", "itype": "상의", 
    "def_ph": 5198,
    "strn": 30,
    "intl": 30,
    "vit": 33,
    "speed_cast": 2
  },
  {
    "name": "<60에픽 판금 하의>",
    "level": 60, "rarity": "Epic", "material": "판금", "itype": "하의", 
    "def_ph": 4331,
    "strn": 33,
    "intl": 24,
    "vit": 30,
    "speed_cast": 2
  },
  {
    "name": "<60에픽 판금 머리어깨>",
    "level": 60, "rarity": "Epic", "material": "판금", "itype": "머리어깨",
    "def_ph": 3465,
    "strn": 24,
    "intl": 24,
    "vit": 26,
    "speed_cast": 2
  },
  {
    "name": "<60에픽 판금 벨트>",
    "level": 60, "rarity": "Epic", "material": "판금", "itype": "벨트",
    "def_ph": 1733,
    "strn": 18,
    "intl": 18,
    "vit": 19,
    "speed_cast": 2
  },
  {
    "name": "<60에픽 판금 신발>",
    "level": 60, "rarity": "Epic", "material": "판금", "itype": "신발",
    "def_ph": 2598,
    "strn": 18,
    "intl": 18,
    "vit": 19,
    "speed_cast": 2,
    "speed_move": 4
  }
]
